### ISSUE TITLE
Default Affinity Settings  - Distribute across nodes.

### ISSUE THREAD

**Issue by straubt1** [hashicorp/terraform-enterprise-helm#104]
## Challenge

Desire to have TFE Pods to be automatically distributed across the available nodes.

In our experience without adding an affinity to our overrides, there is a chance that the 2 of the replicas will land on a single node.

## Environment

GKE
- 3 Control Nodes (n2-standard-4)

TFE Helm
- `replicaCount: 3`

https://github.com/hashicorp/terraform-enterprise-helm/blob/bef7aab1c46794ce326f73608cf953c73231cbc9/values.yaml#L96

## Recommendation

Update the default to something like below to avoid the need to pass this in from the overrides (what I would argue is the typical expected behavior in production).

```
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - terraform-enterprise
        topologyKey: "kubernetes.io/hostname"
```
